### ISSUE TITLE
Deployment with --no-wallet option?

### ISSUE THREAD

**Issue by michielpost** [FleekHQ/IC-Deploy-Action#2]
I'm using the Dank XTC token to pay for canister cycles. https://dank.ooo/
When I deploy to the IC, I use this command: `dfx deploy --network ic --no-wallet`
`--no-wallet` is needed, because there is no canister wallet

Is it possible to supply the option `--no-wallet` using this GitHub Action>?

**Comment by SamueleA** [comment]
You should be able to do this with the new version of the github action
```
        uses: fleekhq/ic-deploy-action@v2
 ```
 
 You can now use the `dfx_params` input which will append parameters to the dfx command.
 
 https://github.com/FleekHQ/IC-Deploy-Action#dfx_params

**Comment by michielpost** [comment]
Thanks, just updated my GitHub Action and it deployed!
